# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test . -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: coverage.txt
