name: build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: test
      run: go test . -race -coverprofile=coverage.txt -covermode=atomic
    - name: upload coverage to codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
        file: ./coverage.txt
        flags: unittests
